import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/side-nav";
import DataProvider from "../utils/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Finance App | Overview",
    template: "Finance App | %s"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return(
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex">
          <SideNav />
          <DataProvider>
            { children }
          </DataProvider>
        </div>
      </body>
    </html>
  )
}

